import { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Sistema',
    description: 'Generated by create next app',
}

export default function Rootlayout({
    children,


}: {
    children: React.ReactNode;

    }) {

    return (
        <div className="min-h-sceen bg-violet-600 max-w-md m-auto">
            <span>{" "} </span>
            {children}
        </div>
    );
}